---
language: python
python: "2.7"

dist: trusty
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  - printf '[defaults]\nroles_path=../' > ansible.cfg

#  - export ANSIBLE_ROLES_PATH="../"

#  - echo $PWD  $USER

  # Basic role syntax check
  - ansible-playbook tests/test.yml -vvi tests/inventory --syntax-check

  # Test Role functionality
  - ansible-playbook tests/test.yml -vvi tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
