---
  
- name: Add Draios GPG key
  apt_key:
    url: "{{ sysdig_gpg_key_url }}"

- name: Get Draios repository source line
  uri:
    url: "{{ sysdig_deb_url }}"
    return_content: yes
  register: repo_str

- name: Add source line to apt sources
  apt_repository:
    repo: "{{ repo_str.content.strip() }}"
    filename: draios

- name: Install sysdig
  apt:
    name: sysdig
    state: present

