---
  
- name: Install Linux Headers
  apt: 
    name: linux-headers-{{ ansible_kernel }}
    state: present
    update_cache: yes
    cache_valid_time: 43200

- name: Include tasks for selected installation type
  include: Debian_{{ sysdig_install_type }}.yml
