---
  
- name: Add Draios GPG key
  rpm_key:
    key: "{{ sysdig_gpg_key_url }}"

- name: Add draios yum repository
  get_url:
    dest: /etc/yum.repos.d/draios.repo
    url: "{{ sysdig_rpm_url }}"
    force: yes

# Add epel-release repo so that sysdig's dependency
# 'dkms' can be installed
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install Linux Headers
  yum: 
    name: kernel-devel-{{ ansible_kernel }}
    state: present

- name: Install sysdig
  yum:
    name: sysdig
    state: present
