---
  
- name: Install Linux Headers
  yum: 
    name: kernel-devel-{{ ansible_kernel }}
    state: present
    update_cache: yes

- name: Include tasks for selected installation type
  include: RedHat_{{ sysdig_install_type }}.yml
